# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\user\Desktop\BLE Project Final\Connection_Parameters\Connection_Parameters.cydsn\Connection_Parameters.cyprj
# Date: Thu, 14 Jul 2016 01:06:55 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 83.333333333333329 -waveform {0 41.6666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\user\Desktop\BLE Project Final\Connection_Parameters\Connection_Parameters.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\user\Desktop\BLE Project Final\Connection_Parameters\Connection_Parameters.cydsn\Connection_Parameters.cyprj
# Date: Thu, 14 Jul 2016 01:06:48 GMT
